# Texts
TRACEROUTE_MEASUREMENT_DESCRIPTION = "Hunter traceroute"

TRACK_STATUS_IN_PROGRESS_DESCRIPTION = "Track in progress"
TRACK_STATUS_FINISHED_DESCRIPTION = "Track finished"
TRACK_STATUS_ERROR_DESCRIPTION = "Track with error"

# Database
DATABASE_ENGINE = "postgresql"
DATABASE_HOST = "localhost"
DATABASE_USERNAME = "postgres"
DATABASE_PASSWORD = "password"
DATABASE_PORT = 5432
DATABASE_NAME = "postgres"
DATABASE_URL = (
    f"{DATABASE_ENGINE}://{DATABASE_USERNAME}:{DATABASE_PASSWORD}@"
    f"{DATABASE_HOST}:{DATABASE_PORT}/{DATABASE_NAME}"
)

# RIPE Atlas endpoints
RIPE_ATLAS_URL = "https://atlas.ripe.net"
RIPE_ATLAS_API_BASE_URL = f"{RIPE_ATLAS_URL}/api/v2"
RIPE_ATLAS_MEASUREMENTS_URL = f"{RIPE_ATLAS_API_BASE_URL}/measurements"
RIPE_ATLAS_PROBES_URL = f"{RIPE_ATLAS_API_BASE_URL}/probes"
